version: 2.1

workflows:
  version: 2
  test:
    jobs:
	  - build-netstandard-2

orbs:
  win: circleci/windows@2.1

jobs:
  build-netstandard-2:
    parameters:
      build-target-framework:
        type: string
        default: netstandard2.0
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:6.0-focal
    environment:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
    steps:
      - checkout
      - restore_cache:
          keys: 
            - deps-<<parameters.build-target-framework>>-{{ checksum "Reportity/Reportity/Reportity.csproj" }}
            # For these two-step builds, we're caching the NuGet dependencies twice:
            # 1. Here, where we're only building CommonSdk itself and not the test project, we cache
            # the packages with a key like "deps-netstandard2.0-xxxx" where "xxxx" only changes if the
            # CommonSdk project file changes.
            # 2. In the test-netcore job, we are loading dependencies for the test project which might
            # vary depending on which framework we're building the test project with. So we cache the
            # dependencies there with a key like "deps-netstandard2.0-netcoreapp2.1-xxxx-yyyy" where
            # the "yyyy" part will change if the project file for the test project changes.
      - run:
          name: "Path List"
          command: dir
	  - run:
          name: restore Reportity.Reportity
          command: dotnet restore Reportity/Reportity/Reportity.csproj
	  - save_cache:
          key: deps-<<parameters.build-target-framework>>-{{ checksum "Reportity/Reportity/Reportity.csproj" }}
          paths:
            - /root/.nuget/packages
	  - run:
          name: build Reportity.Reportity
          command: dotnet build Reportity/Reportity/Reportity.csproj
	  - persist_to_workspace:
          root: Reportity/Reportity/Reportity
          paths:
            - bin
            - obj
